<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="0" failed="4" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-09T12:54:08Z" name="Suite" finished-at="2019-08-09T12:54:32Z" duration-ms="24290">
    <groups>
    </groups>
    <test started-at="2019-08-09T12:54:08Z" name="Test" finished-at="2019-08-09T12:54:32Z" duration-ms="24290">
      <class name="com.atmecs.testscripts.TestRegister">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.atmecs.testscripts.TestRegister@323b36e0]" started-at="2019-08-09T12:54:09Z" name="setUp" finished-at="2019-08-09T12:54:26Z" duration-ms="16757" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyRegistrationPage(com.atmecs.helper.RegistrationData)[pri:0, instance:com.atmecs.testscripts.TestRegister@323b36e0]" started-at="2019-08-09T12:54:26Z" name="verifyRegistrationPage" data-provider="registrationData" finished-at="2019-08-09T12:54:31Z" duration-ms="4929" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[RegistrationData [Email=Abhinaya@gmail.com, FirstName=Abhinaya, LastName=Venkatesh, Password=HeatClinic12, ConfirmPassword=HeatClinic12]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[passed expected [https://10.10.10.232:8443/register             ] but found [https://10.10.10.232:8443/register]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: passed expected [https://10.10.10.232:8443/register             ] but found [https://10.10.10.232:8443/register]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.atmecs.helper.CommonUtilities.verifyassert(CommonUtilities.java:22)
at com.atmecs.pages.UserRegister.registerData(UserRegister.java:27)
at com.atmecs.testscripts.TestRegister.verifyRegistrationPage(TestRegister.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyRegistrationPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.atmecs.testscripts.TestRegister@323b36e0]" started-at="2019-08-09T12:54:31Z" name="tearDown" finished-at="2019-08-09T12:54:32Z" duration-ms="1359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.atmecs.testscripts.TestRegister -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
  <suite started-at="2019-08-09T12:54:43Z" name="Suite (1)" finished-at="2019-08-09T12:54:52Z" duration-ms="9259">
    <groups>
    </groups>
    <test started-at="2019-08-09T12:54:43Z" name="Test" finished-at="2019-08-09T12:54:52Z" duration-ms="9259">
      <class name="com.atmecs.testscripts.TestAddToCart">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.atmecs.testscripts.TestAddToCart@3febb011]" started-at="2019-08-09T12:54:43Z" name="setUp" finished-at="2019-08-09T12:54:49Z" duration-ms="5679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyAddToCart(com.atmecs.helper.RegistrationData)[pri:0, instance:com.atmecs.testscripts.TestAddToCart@3febb011]" started-at="2019-08-09T12:54:49Z" name="verifyAddToCart" data-provider="registrationData" finished-at="2019-08-09T12:54:51Z" duration-ms="2388" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[RegistrationData [Email=Abhinaya@gmail.com, FirstName=Abhinaya, LastName=Venkatesh, Password=HeatClinic12, ConfirmPassword=HeatClinic12]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[passed expected [http://10.10.10.232:8080/                                    ] but found [http://10.10.10.232:8080/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: passed expected [http://10.10.10.232:8080/                                    ] but found [http://10.10.10.232:8080/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.atmecs.helper.CommonUtilities.verifyassert(CommonUtilities.java:22)
at com.atmecs.pages.UserLogin.loginData(UserLogin.java:26)
at com.atmecs.testscripts.TestAddToCart.verifyAddToCart(TestAddToCart.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddToCart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.atmecs.testscripts.TestAddToCart@3febb011]" started-at="2019-08-09T12:54:51Z" name="tearDown" finished-at="2019-08-09T12:54:52Z" duration-ms="1089" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.atmecs.testscripts.TestAddToCart -->
    </test> <!-- Test -->
  </suite> <!-- Suite (1) -->
  <suite started-at="2019-08-09T12:54:33Z" name="Suite (0)" finished-at="2019-08-09T12:54:43Z" duration-ms="10092">
    <groups>
    </groups>
    <test started-at="2019-08-09T12:54:33Z" name="Test" finished-at="2019-08-09T12:54:43Z" duration-ms="10092">
      <class name="com.atmecs.testscripts.TestLogin">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.atmecs.testscripts.TestLogin@79e2c065]" started-at="2019-08-09T12:54:33Z" name="setUp" finished-at="2019-08-09T12:54:39Z" duration-ms="6123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyLoginPage(com.atmecs.helper.RegistrationData)[pri:0, instance:com.atmecs.testscripts.TestLogin@79e2c065]" started-at="2019-08-09T12:54:39Z" name="verifyLoginPage" data-provider="registrationData" finished-at="2019-08-09T12:54:42Z" duration-ms="2685" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[RegistrationData [Email=Abhinaya@gmail.com, FirstName=Abhinaya, LastName=Venkatesh, Password=HeatClinic12, ConfirmPassword=HeatClinic12]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[passed expected [http://10.10.10.232:8080/                                    ] but found [http://10.10.10.232:8080/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: passed expected [http://10.10.10.232:8080/                                    ] but found [http://10.10.10.232:8080/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.atmecs.helper.CommonUtilities.verifyassert(CommonUtilities.java:22)
at com.atmecs.pages.UserLogin.loginData(UserLogin.java:26)
at com.atmecs.testscripts.TestLogin.verifyLoginPage(TestLogin.java:42)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.atmecs.testscripts.TestLogin@79e2c065]" started-at="2019-08-09T12:54:42Z" name="tearDown" finished-at="2019-08-09T12:54:43Z" duration-ms="1056" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.atmecs.testscripts.TestLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite (0) -->
  <suite started-at="2019-08-09T12:55:01Z" name="HeatClinic" finished-at="2019-08-09T12:55:01Z" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- HeatClinic -->
  <suite started-at="2019-08-09T12:54:52Z" name="Suite (2)" finished-at="2019-08-09T12:55:01Z" duration-ms="8820">
    <groups>
    </groups>
    <test started-at="2019-08-09T12:54:52Z" name="Test" finished-at="2019-08-09T12:55:01Z" duration-ms="8820">
      <class name="com.atmecs.testscripts.TestRemoveFromCart">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.atmecs.testscripts.TestRemoveFromCart@77fbd92c]" started-at="2019-08-09T12:54:52Z" name="setUp" finished-at="2019-08-09T12:54:57Z" duration-ms="4995" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyAddToCart(com.atmecs.helper.RegistrationData)[pri:0, instance:com.atmecs.testscripts.TestRemoveFromCart@77fbd92c]" started-at="2019-08-09T12:54:57Z" name="verifyAddToCart" data-provider="registrationData" finished-at="2019-08-09T12:55:00Z" duration-ms="2520" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[RegistrationData [Email=Abhinaya@gmail.com, FirstName=Abhinaya, LastName=Venkatesh, Password=HeatClinic12, ConfirmPassword=HeatClinic12]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[passed expected [http://10.10.10.232:8080/                                    ] but found [http://10.10.10.232:8080/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: passed expected [http://10.10.10.232:8080/                                    ] but found [http://10.10.10.232:8080/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.atmecs.helper.CommonUtilities.verifyassert(CommonUtilities.java:22)
at com.atmecs.pages.UserLogin.loginData(UserLogin.java:26)
at com.atmecs.testscripts.TestRemoveFromCart.verifyAddToCart(TestRemoveFromCart.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1204)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddToCart -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.atmecs.testscripts.TestRemoveFromCart@77fbd92c]" started-at="2019-08-09T12:55:00Z" name="tearDown" finished-at="2019-08-09T12:55:01Z" duration-ms="1211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.atmecs.testscripts.TestRemoveFromCart -->
    </test> <!-- Test -->
  </suite> <!-- Suite (2) -->
</testng-results>
